#base ref = destination
#head ref = source
name: merge-rules

on: pull_request

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge to DEV not coming from main or feature #master
        if: github.base_ref == 'DEV' && (github.head_ref != 'main' && !contains(github.head_ref, 'feature/')) #master
        run: |
          echo "Error: You can only merge main and feature/* branches to DEV"
          exit 1
      - name: Block merge to TEST not coming from DEV
        if: github.base_ref == 'TEST' && github.head_ref != 'DEV'
        run: |
          echo "Error: You can only merge DEV to TEST"
          exit 1
      - name: Block merge to UAT not coming from TEST
        if: github.base_ref == 'UAT' && github.head_ref != 'TEST'
        run: |
          echo "Error: You can only merge TEST to UAT"
          exit 1
      - name: Block merge to PROD not coming from UAT or hotfix
        if: github.base_ref == 'PROD' && (github.head_ref != 'UAT' && !contains(github.head_ref, 'hotfix/'))
        run: |
          echo "Error: You can only merge UAT and hotfix/* branches to PROD"
          exit 1
      - name: Block merge to main not coming from PROD #master
        if: github.base_ref == 'main' && github.head_ref != 'PROD'
        run: |
          echo "Error: You can only merge PROD to main"
          exit 1
      - name: Block merge from feature not coming from feature
        if: contains(github.base_ref, 'feature/') && !contains(github.head_ref, 'feature/')
        run: |
          echo "Error: You can only merge feature branches to feature branches"
          exit 1
      - name: Block any merge to hotfix branches
        if: contains(github.base_ref, 'hotfix/')
        run: |
          echo "Error: You cannot merge into any hotfix branches"
          exit 1
